metric: COCO
num_classes: 1

TrainDataset:
  !COCODataSet
    image_dir: ""
    anno_path: xiaodu_filt_ent_aic_coco_train_cocoformat.json
    dataset_dir: dataset/posedata2d
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: val2017
    anno_path: annotations/person_keypoints_val2017.json
    dataset_dir: dataset/posedata2d/coco

TestDataset:
  !ImageFolder
    anno_path: annotations/instances_val2017.json # also support txt (like VOC's label_list.txt)
    dataset_dir: dataset/posedata2d/coco # if set, anno_path will be 'dataset_dir/anno_path'
